[workspace]
resolver = "2"
members = [
    "crates/agent-fetch",
    "crates/agent-fetch-js",
]

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1

[workspace.lints.rust]
deprecated = "deny"
unused_imports = "warn"
dead_code = "warn"
